G_43 A Trip To Remember/A Trip to Remember/Areas/Admin/Controllers/AirLineController.cs
using Microsoft.AspNetCore.Mvc;
using ATripToRemember.DataAccess;
using ATripToRemember.Models;
using ATripToRemember.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc.Rendering;
using ATripToRemember.Utility;
using Microsoft.AspNetCore.Authorization;

namespace ATripToRemember.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class AirLineController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IWebHostEnvironment hostEnvironment;
        public AirLineController(IUnitOfWork _unitOfWork, IWebHostEnvironment _hostEnvironment)
        {
            unitOfWork = _unitOfWork;
            hostEnvironment = _hostEnvironment;
        }
        public IActionResult Index()
        {
            IEnumerable<AirLine> objAirLineList = unitOfWork.Airline.GetAll();
            return View(objAirLineList);
        }
        public IActionResult Upsert(int? id)
        {
            AirLine airline = new();
            
            if(id==null || id == 0)
            {
                return View(airline);
            }
            else
            {
                airline = unitOfWork.Airline.GetFirstOrDefault(u => u.Id == id);
                return View(airline);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(AirLine obj, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = hostEnvironment.WebRootPath;
                if(file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\airlines\");
                    var extension = Path.GetExtension(file.FileName);
                    if(obj.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.ImageUrl = @"\images\airlines\" + fileName + extension;
                }
                if(obj.Id == 0)
                {
                    unitOfWork.Airline.Add(obj);
                    TempData["success"] = "Airline created successfully";
                }
                else
                {
                    unitOfWork.Airline.Update(obj);
                    TempData["success"] = "Airline updated successfully";
                }
                unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //Region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            var airlineList = unitOfWork.Airline.GetAll();
            return Json(new { data = airlineList });
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = unitOfWork.Airline.GetFirstOrDefault(a => a.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            var oldImagePath = Path.Combine(hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            unitOfWork.Airline.Remove(obj);
            unitOfWork.Save();
            return Json(new { success = true, message = "Airline deleted successfully" });
        }
        //End Region
    }
}

G_43 A Trip To Remember/A Trip to Remember/Areas/Admin/Controllers/FlightController.cs
using Microsoft.AspNetCore.Mvc;
using ATripToRemember.DataAccess;
using ATripToRemember.Models;
using ATripToRemember.Models.ViewModels;
using ATripToRemember.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc.Rendering;
using ATripToRemember.Utility;
using Microsoft.AspNetCore.Authorization;

namespace ATripToRemember.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class FlightController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        public FlightController(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upsert(int? id)
        {
            FlightVM flightVM = new()
            {
                Flight = new(),
                AirlineList = unitOfWork.Airline.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
            };
            if(id==null || id==0)
            {
                return View(flightVM);
            }
            else
            {
                flightVM.Flight = unitOfWork.Flight.GetFirstOrDefault(u => u.Id == id);
                return View(flightVM);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(FlightVM obj)
        {
            if(obj.Flight.StartingLocation == obj.Flight.Destination)
            {
                ModelState.AddModelError("Flight.Destination", "Destination and Starting Location cannot be same");
            }
            if(obj.Flight.StartingTime <= DateTime.Now)
            {
                ModelState.AddModelError("Flight.StartingTime", "Date and Time is not valid");
            }
            if(obj.Flight.ReachingTime <= obj.Flight.StartingTime)
            {
                ModelState.AddModelError("Flight.ReachingTime", "Reaching Time should be greater than Starting Time");
            }
            if (ModelState.IsValid)
            {
                if (obj.Flight.Id == 0)
                {
                    unitOfWork.Flight.Add(obj.Flight);
                    TempData["success"] = "Flight created successfully";
                }
                else
                {
                    unitOfWork.Flight.Update(obj.Flight);
                    TempData["success"] = "Flight updated successfully";
                }
                unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //Region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            var flightList = unitOfWork.Flight.GetAll(includeProperties: "Airline");
            return Json(new { data = flightList });
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = unitOfWork.Flight.GetFirstOrDefault(a => a.Id == id);
            if (obj == null)
            {
                return Json(new {success = false, message = "Error while deleting"});
            }
            unitOfWork.Flight.Remove(obj);
            unitOfWork.Save();
            return Json(new {success = true, message = "Flight deleted successfully"});
        }
        //End Region
    }
}

G_43 A Trip To Remember/A Trip to Remember/Areas/Admin/Controllers/HotelController.cs
using ATripToRemember.DataAccess.Repository.IRepository;
using ATripToRemember.Models;
using Microsoft.AspNetCore.Mvc;
using ATripToRemember.Utility;
using Microsoft.AspNetCore.Authorization;

namespace ATripToRemember.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class HotelController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IWebHostEnvironment hostEnvironment;
        public HotelController(IUnitOfWork _unitOfWork, IWebHostEnvironment _hostEnvironment)
        {
            unitOfWork = _unitOfWork;
            hostEnvironment = _hostEnvironment;
        }
        public IActionResult Index()
        {
            IEnumerable<Hotel> objHotelList = unitOfWork.Hotel.GetAll();
            return View(objHotelList);
        }
        public IActionResult Upsert(int? id)
        {
            Hotel hotel = new();

            if (id == null || id == 0)
            {
                return View(hotel);
            }
            else
            {
                hotel = unitOfWork.Hotel.GetFirstOrDefault(u => u.Id == id);
                return View(hotel);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Hotel obj, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\hotels\");
                    var extension = Path.GetExtension(file.FileName);
                    if (obj.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.ImageUrl = @"\images\hotels\" + fileName + extension;
                }
                if (obj.Id == 0)
                {
                    unitOfWork.Hotel.Add(obj);
                    TempData["success"] = "Hotel added successfully";
                }
                else
                {
                    unitOfWork.Hotel.Update(obj);
                    TempData["success"] = "Hotel updated successfully";
                }
                unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //Region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            var hotelList = unitOfWork.Hotel.GetAll();
            return Json(new { data = hotelList });
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = unitOfWork.Hotel.GetFirstOrDefault(a => a.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            var oldImagePath = Path.Combine(hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            unitOfWork.Hotel.Remove(obj);
            unitOfWork.Save();
            return Json(new { success = true, message = "Hotel deleted successfully" });
        }
        //End Region
    }
}

G_43 A Trip To Remember/A Trip to Remember/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ATripToRemember</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ATripToRemember.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">A Trip To Remember</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="AirLine" asp-action="Index">AirLines</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Flight" asp-action="Index">Flights</a>
                            </li>*@
                        @if(User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Airline" asp-action="Index">Airlines</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Flight" asp-action="Index">Flights</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Hotel" asp-action="Index">Hotels</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create Admin</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Booking" asp-action="Index">
                                    <i class="bi bi-ticket"></i> &nbsp; Bookings
                                </a>
                            </li>
                        }
                        @if(User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Booking" asp-action="Index">
                                    <i class="bi bi-ticket"></i> &nbsp; Bookings
                                </a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Flight" asp-action="Index">
                                Flights
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Hotel" asp-action="Index">
                                Hotels
                            </a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                    @*<form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                        </form>*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-primary">
        <div class="container">
            &copy; 2022 - ATripToRemember - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/um3hvywjs3e8etp66bl8srz6awu5nvk09c0udl4udg13v8qo/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

G_43 A Trip To Remember/A Trip to Remember/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');    
    </script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}