G-28/Code/bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
    path('order/', include('order.urls')),
    path('',include("store.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

G-28/Code/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
	path('', views.index, name = "index"),
	path('login', views.signin, name="signin"),
	path('logout', views.signout, name="signout"),
	path('registration', views.registration, name="registration"),
	path('book/<int:id>', views.get_book, name="book"),
	path('books', views.get_books, name="books"),
	path('category/<int:id>', views.get_book_category, name="category"),
	path('writer/<int:id>', views.get_writer, name = "writer"),
]

G-28/Code/templates/store/base.html
<!DOCTYPE html>
<html>
<head>
	<title> Old Book Store</title>
	{% load staticfiles %}
	<script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/slick-theme.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/skdslider.css' %}"> 
</head>
<body>
<div class="pre_loader gray_bg text-center">
    <div class="loader">
        <div><div><div><div></div></div></div></div>
    </div>
</div>
{% include 'store/bin/header.html' %}

{% block headermenu %} {% endblock %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-2">
			{% include 'store/bin/sidebar.html' %}
		</div>
		<div class="col-sm-10">
			{% block container %}{% endblock %}
		</div>
		
	</div>
</div>
<div id="snackbar"></div>

{% include 'store/bin/footer.html' %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-touchspin/4.2.5/jquery.bootstrap-touchspin.js" type="text/javascript"></script>
<script src="{% static 'js/skdslider.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Readmore.js/2.2.1/readmore.js" type="text/javascript"></script>
<script src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script>
<script src="{% static 'js/main.js' %}"></script> 
{% block scripts %}{% endblock %}
</body>
</html>

G-28/Code/templates/store/book.html
{% extends 'store/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load customfunction %}
{% block container %}
			<div class="row">
				<div class="col-sm-12">
					<div class="row">
						<div class="col-sm-3">
							<div class="grid-item">
								<div class="view-details" style="cursor:pointer">
									<img id="product_image" class="lookInsideImg" src="{{ book.coverpage.url }}">
								</div>
							</div>	
							<div class="lookInsideDiv" style="display: none;">
								<div class="exitBtn"></div>
								<div class="pagesArea">
									<ul class="list-unstyled pages">
										<li><img src="{{ book.bookpage.url }}"></li>
									</ul>
								</div>
							</div>				
						</div>
						
						<div class="col-sm-6">
							<div class="product-information">
								<h4>{{ book.name }}</h4>
								<p style="margin: 0px">by <a style="font-weight:bold" href="{% url 'store:writer' id=book.writer.id %}">{{ book.writer }}</a></p>
								<div class='rating'>
									{{ book.totalrating|averagerating:book.totalreview }}
									<a href='#getreview'><span class='totalrating'>{{ book.totalreview|add:-1 }} Reviews</span></a>
								</div>
								<article class="text-justify" style="margin-top:10px;">
									{{ book.description }}
								</article>

							</div>
						</div>
						<div class="col-sm-3">
							<div class="pricebox">
								<p>₹Price: <span> {{ book.price }}</span></p>
								<button class="btn btn-danger" id="addTocart" data-book-id="{{ book.id }}">
									<i class="fa fa-shopping-cart""></i>Add to cart
								</button>
							</div>
						</div>
					</div>	
				</div>

			    <div class="col-sm-9 mt-5" id="getreview">
					{% if messages %}
						<div class="messages">
						    {% for message in messages %}
						    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
						    {% endfor %}
						</div>
					{% endif %}	
					<div class="rating-stars text-left">
						<ul id="stars">
						  <li id="azaa" class="star" data-value="1"> <i class="fa fa-star fa-fw"></i> </li>
						  <li id="azbb" class="star" data-value="2"> <i class="fa fa-star fa-fw"></i> </li>
						  <li id="azcc" class="star" data-value="3"> <i class="fa fa-star fa-fw"></i> </li>
						  <li id="azdd" class="star" data-value="4"> <i class="fa fa-star fa-fw"></i> </li>
						  <li id="azee" class="star" data-value="5"> <i class="fa fa-star fa-fw"></i> </li>
						</ul>
					</div>		
				   <form action="" method="POST" class="needs-validation" novalidate="">
				   	{% csrf_token %}
					
						<div class="form-group">
							{{ form.review_star|as_crispy_field }}
						</div>
						<div class="form-group">
							{{ form.review_text|as_crispy_field }}
						</div>
						<div class="form-group">
							<button class="btn btn-danger" type="submit" style="color: #fff">Submit </button>
						</div>
				   </form>	
					{% for lreview in rreview %}
					<div class="card">
						<div class="card-body">
							<img src="{% static 'images/profile.png' %}"/>
							<b> {{ lreview.customer }} </b>
							<div class='rating'>
								{{ lreview.review_star|averagerating:1 }}
							</div>
							<div class="given_review_date">
								<span style="color:#555;"> {{ lreview.created }}</span>
							</div>
							<p style="margin-top: 10px"> {{ lreview.review_text }} </p>
						 </div>
					</div>
					{% endfor %}
					
					<div class="d-pagination">
					    <ul class="pagination">
						{% if rreview.has_previous %}
							<li class="page-item">
								<a class="page-link" href="?page=1">First</a>
							</li>								
							<li class="page-item">
								<a class="page-link" href="?page={{ rreview.previous_page_number }}">Previous</a>
							</li>
						{% endif %}
						{% for ord in rreview.paginator.page_range %}
							{% if rreview.number == ord %}
								<li class="page-item active">
									<span class="page-link">{{ ord }}
										<span class="sr-only">(current)</span>
									</span>
								</li>
							{% elif ord > rreview.number|add:'-3' and ord < rreview.number|add:'3' %}
								<li class="page-item">
									<a class="page-link" href="?page={{ ord }}">{{ ord }}</a>
								</li>

							{% endif %}

						{% endfor %}
						 {% if rreview.has_next %}
							<li class="page-item">
								<a class="page-link" href="?page={{ rreview.next_page_number }}">Next</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="?page={{ rreview.paginator.num_pages }}">Last</a>
							</li>
						{% endif %}
					    </ul>
					</div>		
				</div>
			</div>

{% endblock %}


{% block scripts %}
<script type="text/javascript">
	$(document).on('ready', function() {
		$(document).on('click', '.lookInsideImg,.lookInsideBg', function (e) {
			$('div.overlay').fadeIn(500);
			$('div.lookInsideDiv').fadeIn(500);
		});
	   
	   $(document).on('click', 'div.lookInsideDiv div.exitBtn', function () {
			$('div.overlay').fadeOut(500);
			$('div.lookInsideDiv').fadeOut(500);
			refCaro($('#bookDR99'));
		});
		$(document).on('click', 'div.overlay', function () {
			$('div.overlay').fadeOut(500);
			$('div.lookInsideDiv').fadeOut(500);
			refCaro($('#bookDR99'));
			return false
		});	
	});
</script>

{% endblock %}

G-28/Code/templates/store/category.html
{% extends 'store/base.html' %}
{% load customfunction %}
{% block container %}
			<div class="row">
				{% for item in book %}
				<div class = 'col-sm-3'>
					<div class="book-wrapper text-center">
						<div class="coverpage">
							<img src="{{ item.coverpage.url }}"/>
						</div>
						<a href="{% url 'store:book' id=item.id %}">{{ item.name }}</a>
						<a href="{% url 'store:writer'  id=item.writer.id %}">{{ item.writer }}</a>
						<div class="rating">
							{{ item.totalrating|averagerating:item.totalreview }}
							<span class="totalrating">{{ item.totalreview|add:-1 }}</span>
						</div>
						<p> ₹{{ item.price }}</p>
						<button class="btn btn-danger" id="addTocart" data-book-id="{{ item.id }}">
								<i class="fa fa-shopping-cart""></i>Add to cart
						</button>
					</div>
				</div>
				{% endfor %}

			</div>
			{% if book|length > 0 %}
			<div class="d-pagination">
			    <ul class="pagination">
				{% if book.has_previous %}
					<li class="page-item">
						<a class="page-link" href="?page=1">First</a>
					</li>								
					<li class="page-item">
						<a class="page-link" href="?page={{ book.previous_page_number }}">Previous</a>
					</li>
				{% endif %}
				{% for ord in book.paginator.page_range %}
					{% if book.number == ord %}
						<li class="page-item active">
							<span class="page-link">{{ ord }}
								<span class="sr-only">(current)</span>
							</span>
						</li>
					{% elif ord > book.number|add:'-3' and ord < book.number|add:'3' %}
						<li class="page-item">
							<a class="page-link" href="?page={{ ord }}">{{ ord }}</a>
						</li>

					{% endif %}

				{% endfor %}
				 {% if book.has_next %}
					<li class="page-item">
						<a class="page-link" href="?page={{ book.next_page_number }}">Next</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="?page={{ book.paginator.num_pages }}">Last</a>
					</li>
				{% endif %}
			    </ul>
			</div>
			{% else %}
			<h3 class="text-center mt-5">There are no books Found.</h3>
			{% endif %}	

{% endblock %}

G-28/Code/templates/store/index.html
{% extends 'store/base.html' %}
{% load static %}
{% load customfunction %}
{% block headermenu %}

{% endblock %}

			{% block container %}
			<div class="row">
				
						<ul id="demo3">
							{% for sld in slide %}
							<li><img height="100" src="{{ sld.slideimg.url }}"/></li>
							{% endfor %}
						</ul>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="titleheader">
						<h3 class="h2header text-center">New Published Book</h3>
						<a href="#">See All</a>
					</div>
					<div class="regulara sliderzx">
						{% for item in newbooks %}
						<div class="book-wrapper text-center">
							<div class="coverpage">
								<img src="{{ item.coverpage.url }}"/>
							</div>
							<a href="{% url 'store:book' id=item.id %}">{{ item.name|text_short }}</a>
							<a href="{% url 'store:writer' id=item.writer.id %}">{{ item.writer }}</a>
							<div class="rating">
								{{ item.totalrating|averagerating:item.totalreview }}
								<span class="totalrating">{{ item.totalreview|add:-1 }}</span>
							</div>
							<p> ₹{{ item.price }}</p>
							<button class="btn btn-danger" id="addTocart" data-book-id="{{ item.id }}">
									<i class="fa fa-shopping-cart""></i>Add to cart
								</button>
						</div>
						{% endfor %}
					</div>
				</div>

				<div class="col-sm-12">
					<div class="titleheader">
						<h3 class="h2header text-center">Top Selling Book</h3>
					</div>
					<div class="regulara sliderzx">
						{% for p in newbooks %}
						<div class="book-wrapper text-center">
							<div class="coverpage">
								<img src="{{ p.coverpage.url }}"/>
							</div>
							<a href="{% url 'store:book' id=p.id %}">{{ p.name|text_short }}</a>
							<a href="{% url 'store:writer'  id=p.writer.id %}">{{ p.writer }}</a>
							<div class="rating">
								{{ p.totalrating|averagerating:p.totalreview }}
								<span class="totalrating">{{ p.totalreview|add:-1 }}</span>
							</div>
							<p> ₹{{ p.price }}</p>
							<button class="btn btn-danger" id="addTocart" data-book-id="{{ p.id }}">
									<i class="fa fa-shopping-cart""></i>Add to cart
								</button>
						</div>
						{% endfor %}
					</div>
				</div>
			</div> 
			{% endblock %}

G-28/Code/templates/store/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Book Store Sign In</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>


<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-md-4 col-sm-3">
			<div class="signin-form">
				{% if messages %}
				<div class="messages">
				    {% for message in messages %}
				    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
				    {% endfor %}
				</div>
				{% endif %}
				<h3> Sign In</h3>	
				<form action="" method="POST" class="auth-validate-form">
					{% csrf_token %}
					<div class="form-group">
					   <label>Username</label>
					   <input type="text" name="user" class="form-control">
					</div>
					<div class="form-group">
					   <label>Password</label>
					   <input type="password" name="pass" class="form-control">
					</div>
					<button type="submit" class="btn btn-danger">Login</button>
				</form>
				<a href="#">Forgot your password?</a>
				<div class="a-divider-break"><h5>New to BookStore?</h5></div>
				<a class="btn btn-default" href="{% url 'store:registration' %}">Create you BookStore account</a>
			</div> 
		</div>
	</div>
</div>

</body>
</html>

G-28/Code/templates/store/signup.html
<!DOCTYPE html>
<html>
<head>
	<title>Book Store Registration</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-md-4 col-sm-3">
			<div class="signup-form">
				<div class="messages"></div>	
				<h3> Create account</h3>	
				<form action="" method="POST" class="auth-validate-form">
					{% csrf_token %}
					{% for field in form %}
					    <div class="form-group registration-form">
					        {{ field.label_tag }}<br>
					        {{ field }}

					        {% if field.help_text %}{% endif %}

					        {% for error in field.errors %}
					          <p style="color: red;font-size: 13px">{{ error }}</p>
					        {% endfor %}
					    </div>
					{% endfor %}
					<button class="btn btn-danger">Create you BookStore account</button>
				</form>
				<div class="a-divider-break"></div>
				<div class="a-divider-inner">
					<div class="a-row">
					    Already have an account?
					    <a class="a-link-emphasis" href="{% url 'store:signin' %}"><i class='fa fa-caret-right'></i> Sign in</a>
					</div>						
				</div>
			</div> 
		</div>
	</div>
</div>
</body>
</html>

G-28/Code/templates/store/writer.html
{% extends 'store/base.html' %}
{% load static %}
{% load customfunction %}
{% block container %}
			<div class="row">
				<div class="col-sm-12">
					<div class="row">
						<div class="col-sm-3">
							<div class="view-details">
								<img src="{{ wrt.pic.url }}">
							</div>
						</div>
						
						<div class="col-sm-8">
							<div class="product-information">
								<h3>{{ wrt.name }}</h3>
								<article class="text-justify" style="margin-top:10px;">{{ wrt.bio }}</article>

							</div>
						</div>
					</div>	
				</div>

				<div class="col-sm-12">
					<div class="titleheader">
						<h3 class="h2header text-center">Published Books</h3>
					</div>
					<div class="regulara sliderzx">
						{% for item in book %}
						<div class="book-wrapper text-center">
							<div class="coverpage">
								<img src="{{ item.coverpage.url }}"/>
							</div>
							<a href="{% url 'store:book' id=item.id %}">{{ item.name|text_short }}</a>
							<a href="{% url 'store:writer' id=item.writer.id %}">{{ item.writer }}</a>
							<div class="rating">
								{{ item.totalrating|averagerating:item.totalreview }}
								<span class="totalrating">{{ item.totalreview|add:-1 }}</span>
							</div>
							<p> ${{ item.price }} </p>
							<button class="btn btn-danger" id="addTocart" data-book-id="{{ item.id }}">
									<i class="fa fa-shopping-cart""></i>Add to cart
								</button>


						</div>
						{% endfor %}
					</div>
				</div>
			</div>
{% endblock %}